library(rmarkdown)
date <- as.character(date())
dir.create(date)
source("downloadRawData.R")
source("cleanData.R")
source("clearData2.R")
source("clearData3.R")
dir.create("raports")
rmarkdown::render(file.path("raportPrzyslowki.Rmd"), output_dir = file.path(date, "raports"))
rmarkdown::render(file.path("raportEfektEpistemiczny.Rmd"), output_dir = file.path(date, "raports"))
rmarkdown::render(file.path("raportWymyslonePrzyslowki.Rmd"), output_dir = file.path(date, "raports"))
