library(shiny)

shinyUI(fluidPage(
  titlePanel("Przyczynowość i działanie - badanie do Bochum"),
  fluidRow(column(2,
    h4("Wybierz filtry:"),
    h5("Pierwsze ogniwo:"),
    checkboxInput("dzialanie_1", "Działanie", value=TRUE),
    checkboxInput("dzianie_sie_1", "Dzianie się", value=TRUE),
    h5("Drugie ogniwo:"),
    checkboxInput("dzialanie_2", "Działanie", value=TRUE),
    checkboxInput("dzianie_sie_2", "Dzianie się", value=TRUE),
    h5("Skutek moralny"),
    checkboxInput("pozytywny", "Pozytywny", value=TRUE),
    checkboxInput("negatywny", "Negatywny", value=TRUE),
    checkboxInput("neutralny", "Neutralny", value=TRUE),
    h5("Zmiana i brak zmiany"),
    checkboxInput("brak_zmiany", "Brak zmiany", value=TRUE),
    checkboxInput("zmiana", "Zmiana", value=TRUE),
    
    h4("Wybierz czynniki:"),
    checkboxInput("factor_zmiana", "Zmiana czy brak zmiany", value=TRUE),
    checkboxInput("factor_pierwsze_ogniwo", "Pierwsze ogniwo", value=TRUE),
    checkboxInput("factor_drugie_ogniwo", "Drugie ogniwo", value=TRUE),
    checkboxInput("factor_skutek_moralny", "Skutek moralny", value=TRUE),
    h4("Wybierz osobę:")
,
selectInput("osoba", "Osoba:",
                 c("Chłopiec" = "chlopiec",
                   "Dozorca" = "dozorca",
                   "Mieszkańcy" = "mieszkancy",
                   "Robotnicy" = "robotnicy",
                   "Malinowska" = "malinowska"))),
  column(4,
    h2("Pytanie pierwsze"),
    tableOutput("model_pierwszy"),
    h3("Średnia"),
    tableOutput("srednia_pierwsza"),
    h3("Odchylenie standardowe"),
    textOutput("odchylenie_pierwsze"),
    h2("Pytanie drugie"),
    tableOutput("model_drugi"),
    h3("Średnia"),
    tableOutput("srednia_druga"),
    h3("Odchylenie standardowe"),
    textOutput("odchylenie_drugie"),
    h2("Odpowiedzialność"),
    h3("Tabela częstościowa"),
    tableOutput("odpowiedzialny"),
    h3("Tabela proporcjonalna"),
    tableOutput("odpowiedzialny_2")
    ),
column(4,
       h2("Pytanie pierwsze"),
       tableOutput("D_model_pierwszy"),
       h3("Średnia"),
       tableOutput("D_srednia_pierwsza"),
       h3("Odchylenie standardowe"),
       textOutput("D_odchylenie_pierwsze"),
       h2("Pytanie drugie"),
       tableOutput("D_model_drugi"),
       h3("Średnia"),
       tableOutput("D_srednia_druga"),
       h3("Odchylenie standardowe"),
       textOutput("D_odchylenie_drugie"),
       h2("Odpowiedzialność"),
       h3("Tabela częstościowa"),
       tableOutput("D_odpowiedzialny"),
       h3("Tabela proporcjonalna"),
       tableOutput("D_odpowiedzialny_2")),
column(2,
       h4("Wybierz filtry:"),
       h5("Pierwsze ogniwo:"),
       checkboxInput("D_dzialanie_1", "Działanie", value=TRUE),
       checkboxInput("D_dzianie_sie_1", "Dzianie się", value=TRUE),
       h5("Drugie ogniwo:"),
       checkboxInput("D_dzialanie_2", "Działanie", value=TRUE),
       checkboxInput("D_dzianie_sie_2", "Dzianie się", value=TRUE),
       h5("Skutek moralny"),
       checkboxInput("D_pozytywny", "Pozytywny", value=TRUE),
       checkboxInput("D_negatywny", "Negatywny", value=TRUE),
       checkboxInput("D_neutralny", "Neutralny", value=TRUE),
       h5("Zmiana i brak zmiany"),
       checkboxInput("D_brak_zmiany", "Brak zmiany", value=TRUE),
       checkboxInput("D_zmiana", "Zmiana", value=TRUE),
       
       h4("Wybierz czynniki:"),
       checkboxInput("D_factor_zmiana", "Zmiana czy brak zmiany", value=TRUE),
       checkboxInput("D_factor_pierwsze_ogniwo", "Pierwsze ogniwo", value=TRUE),
       checkboxInput("D_factor_drugie_ogniwo", "Drugie ogniwo", value=TRUE),
       checkboxInput("D_factor_skutek_moralny", "Skutek moralny", value=TRUE),
       h4("Wybierz osobę:")
       ,
       selectInput("D_osoba", "Osoba:",
                   c("Chłopiec" = "chlopiec",
                     "Dozorca" = "dozorca",
                     "Mieszkańcy" = "mieszkancy",
                     "Robotnicy" = "robotnicy",
                     "Malinowska" = "malinowska")))

)))
